<?php

echo $block->getLayout()

           ->createBlock('Magento\Cms\Block\Block')

           ->setBlockId('banner-homepage')

           ->toHtml();        
              
?>

<script>
  //    require([
  //     'jquery',
  //     'slick',
  //     'domReady!'
  //  ], function ($) {
  //     $(".outdoor-content").slick({
  //        dots: false,
  //        infinite: true,
  //        speed: 300,
  //        slidesToShow: 5,
  //        slidesToScroll: 5
  //     });
  //  });
   require([
      'jquery',
      'slick',
      'domReady!'
   ], function ($) {
      $(".product-items").slick({
         dots: false,
         infinite: true,
         speed: 300,
         slidesToShow: 4,
         slidesToScroll: 1
      });
   });
</script>
<!-- <script>
$('.product-items').slick({
  dots: true,
  infinite: false,
  speed: 300,
  slidesToShow: 4,
  slidesToScroll: 4,
  responsive: [
    {
      breakpoint: 1024,
      settings: {
        slidesToShow: 3,
        slidesToScroll: 3,
        infinite: true,
        dots: true
      }
    },
    {
      breakpoint: 600,
      settings: {
        slidesToShow: 2,
        slidesToScroll: 2
      }
    },
    {
      breakpoint: 480,
      settings: {
        slidesToShow: 1,
        slidesToScroll: 1
      }
    }
  ]
});
</script> -->